/-
# MiniCurvesSurfaces: Morphisms — Birational Equivalence (L2/L3)
-/

import MiniCurvesSurfaces.Core.Basic
import MiniCurvesSurfaces.Core.Laws
import MiniCurvesSurfaces.Morphisms.Hom

namespace MiniCurvesSurfaces

structure RationalMap where
  fst : RationalFunction
  snd : RationalFunction
  name : String
  deriving Repr

def RationalMap.eval (φ : RationalMap) (x y : Int) : Option (Int × Int) :=
  match φ.fst.evalAt x y, φ.snd.evalAt x y with
  | some p, some q => some (p, q)
  | _, _ => none

def RationalMap.isDefinedAt (φ : RationalMap) (x y : Int) : Bool :=
  φ.fst.isRegularAt x y && φ.snd.isRegularAt x y

/-! ## Birational Parametrizations of Singular Cubics

The nodal cubic y^2 = x^3 + x^2 and the cuspidal cubic y^2 = x^3
are both birationally equivalent to A^1 (genus 0). -/

def nodalCubicParametrization (t : Int) : Int × Int :=
  (t*t - 1, t*(t*t - 1))

def cuspidalCubicParametrization (t : Int) : Int × Int :=
  (t*t, t*t*t)

/-! ## Blow-Ups and Resolution of Singularities

Blowing up a point on a surface replaces it with an exceptional divisor
E ≅ P^1 with E^2 = -1. For curves, blow-ups resolve singularities.
Genus change: g(C~) = g(C) - m(m-1)/2 for an m-fold point. -/

def exceptionalDivisorSelfIntersection : Int := -1

def properTransformIntersection (multiplicity : Nat) : Nat := multiplicity

def genusAfterBlowupSingular (g multiplicity : Nat) : Nat :=
  let delta := multiplicity * (multiplicity - 1) / 2
  if delta <= g then g - delta else 0

/-! ## Cremona Transformations — L8

The standard quadratic Cremona transformation of P^2:
σ: [x:y:z] -> [yz : xz : xy].
σ^2 = id and σ is undefined at [1:0:0], [0:1:0], [0:0:1].
deg(σ(C)) = 2d - m1 - m2 - m3 for a curve with multiplicities mi. -/

def cremonaTransform (x y z : Int) : Int × Int × Int := (y*z, x*z, x*y)

def cremonaDegreeFormula (d m1 m2 m3 : Nat) : Int :=
  (2*d : Int) - (m1 : Int) - (m2 : Int) - (m3 : Int)

theorem cremonaConicToLine : cremonaDegreeFormula 2 1 1 1 = 1 := by
  unfold cremonaDegreeFormula; decide

theorem cremonaCubicToCubic : cremonaDegreeFormula 3 1 1 0 = 4 := by
  unfold cremonaDegreeFormula; decide

/-! ## Resolution of Singularities for Curves — L3

Any irreducible algebraic curve C over a field of characteristic 0
admits a resolution of singularities: there exists a smooth projective
curve C̃ and a birational morphism π: C̃ -> C which is an isomorphism
over the smooth locus. For plane curves, this is achieved by
repeated blow-ups at singular points.

Genus formula for the normalization: g(C̃) = p_a(C) - Σ_P δ_P
where δ_P = length(Õ_{C,P} / O_{C,P}) is the delta-invariant. -/

def resolutionGenus (pa : Nat) (deltaSum : Nat) : Nat :=
  if deltaSum <= pa then pa - deltaSum else 0

/-- For a nodal curve with δ nodes: g(C̃) = p_a - δ.
    Example: nodal plane cubic (d=3, p_a=1, 1 node) => g(C̃) = 0. -/
def nodalCurveResolvedGenus (pa nodes : Nat) : Nat := pa - nodes

/-- For a cuspidal curve: the delta-invariant of an ordinary cusp
    (multiplicity 2, single tangent) is 1. So a cuspidal cubic resolves
    to a rational curve (genus 0). -/
def cuspidalCurveResolvedGenus (pa : Nat) (cusps : Nat) : Nat := pa - cusps

theorem nodalCubicIsRational : nodalCurveResolvedGenus 1 1 = 0 := by
  unfold nodalCurveResolvedGenus; decide

theorem cuspidalCubicIsRational : cuspidalCurveResolvedGenus 1 1 = 0 := by
  unfold cuspidalCurveResolvedGenus; decide

/-! ## Birational Geometry of Surfaces — L8

Two smooth projective surfaces S, S' are birationally equivalent iff
they are related by a sequence of blow-ups and blow-downs at points.

Minimal models: a surface is minimal if it contains no (-1)-curves.
  - Ruled surfaces: minimal model is P^1-bundle over a curve
  - Non-ruled: minimal model has K nef (unique up to isomorphism)

Castelnuovo theorem: if S is rational, any birational map S -> S'
is a composition of blow-ups and blow-downs. -/

def areBirationallyEquivalentViaBlowups : String :=
  "Two surfaces S, S' are birational ⇔ connected by blow-ups/blow-downs"

/-! ## Cremona Group — L8

The Cremona group Cr(2) = Bir(P^2) is the group of birational
automorphisms of P^2. It is generated by PGL(3) and the standard
quadratic transformation σ: [x:y:z] → [yz:xz:xy].

Properties:
  - Cr(2) is not simple (contains normal subgroups)
  - Every finite subgroup of Cr(2) is conjugate to a subgroup of
    Aut(S) for some rational surface S
  - Cr(n) for n ≥ 3 is much more complex (no complete generators known) -/

def cremonaGroupProperties : List String :=
  ["Cr(2) = Bir(P^2), generated by PGL(3) and σ",
   "Cr(1) = PGL(2) (every birational map of P^1 is an automorphism)",
   "σ^2 = id, σ ∘ PGL(3) generates Cr(2)",
   "No simple set of generators known for Cr(n), n ≥ 3"]

def quadraticCremonaInverse (x y z : Int) : Bool :=
  let (x', y', z') := cremonaTransform x y z
  let (x'', y'', z'') := cremonaTransform x' y' z'
  x'' == x && y'' == y && z'' == z

/-! ## Sarkisov Program — L8

The Sarkisov program decomposes any birational map between
Mori fiber spaces into elementary links:
  X₀ -→ X₁ -→ ... -→ Xₙ = Y

Each link is one of four types, involving blow-ups, flips, or
Mori fiber space structures. For surfaces, this is simpler:
every birational map factors into blow-ups and blow-downs. -/

def sarkisovProgramSurfaces : String :=
  "For surfaces: Sarkisov link = blow-up or blow-down of (-1)-curve"

/-! ## #eval -/

#eval cremonaTransform 1 2 3
#eval cremonaTransform 0 1 1
#eval nodalCubicParametrization 2
#eval cuspidalCubicParametrization 2
#eval genusAfterBlowupSingular 3 2
#eval genusAfterBlowupSingular 3 1
#eval cremonaDegreeFormula 2 1 1 1
#eval cremonaDegreeFormula 3 1 1 0

#eval "── Resolution and Cremona ──"
#eval resolutionGenus 1 1
#eval resolutionGenus 3 3
#eval nodalCurveResolvedGenus 1 1
#eval nodalCurveResolvedGenus 3 2
#eval cuspidalCurveResolvedGenus 1 1
#eval cuspidalCurveResolvedGenus 3 1
#eval areBirationallyEquivalentViaBlowups
#eval quadraticCremonaInverse 1 2 3
#eval quadraticCremonaInverse 2 3 5
#eval sarkisovProgramSurfaces
#eval cremonaGroupProperties

end MiniCurvesSurfaces