import MiniObjectKernel.Core.Basic
import MiniModuliSpaces.Core.Basic
import MiniModuliSpaces.Morphisms.Hom

namespace MiniModuliSpaces

/-
# Equivalences of Moduli Spaces (L2-L3)
Birational maps, birational equivalences, rational maps between moduli spaces.
-/

/-- An equivalence of moduli problems: an isomorphism of the
associated moduli functors. This captures the idea that two
moduli problems classify the same objects. -/
structure ModuliEquivalence where
  problem1 : ModuliProblem
  problem2 : ModuliProblem
  forward : ModuliProblemMorphism
  inverse : ModuliProblemMorphism
  leftInverse : Bool
  rightInverse : Bool


/-- A birational map between moduli spaces: an isomorphism
on dense open subsets. Important for comparing different
compactifications of the same moduli problem. -/
structure BirationalMap where
  source : CoarseModuliSpace
  target : CoarseModuliSpace
  domainOfDefinition : List Int
  imageOfDefinition : List Int
  mapOnDomain : List Int -> List Int
  isDenseDomain : Bool
  isDenseImage : Bool


/-- M_g and its Deligne-Mumford compactification M?_g are birational.
The boundary M?_g \ M_g has codimension 2 for g  2. -/
structure MgCompactificationBirational where
  genus : Nat
  openModuli : ModuliOfCurves
  compactModuli : DeligneMumfordCompactification
  inclusionMap : BirationalMap
  boundaryCodimension : Nat


/-- Wall-crossing: as stability parameters vary, the moduli space
changes via birational modifications (flips).
This is the VGIT (Variation of GIT) phenomenon. -/
structure WallCrossing where
  parameterSpace : List Int
  walls : List (List Int)
  chambers : List (List Int)
  moduliSpacesPerChamber : List (Prod Nat CoarseModuliSpace)
  isFlip : Bool


/-- A flip diagram: M+ and M- are birational moduli spaces
related by a flip with respect to a stability parameter t.
Both map to a common (singular) space M0. -/
structure FlipDiagram where
  M_plus : CoarseModuliSpace
  M_minus : CoarseModuliSpace
  M_zero : CoarseModuliSpace
  contraction_plus : CoarseModuliMorphism
  contraction_minus : CoarseModuliMorphism
  isDQFlip : Bool


/-- The Grothendieck ring of varieties K_0(Var):
generated by isomorphism classes [X] with relations
[X] = [Z] + [X\Z] for closed Z ? X.
Motivic invariants of moduli spaces. -/
structure GrothendieckRing where
  varieties : List (List Int)
  equivalenceClasses : List (List Int)
  scissorRelations : List (List Int -> List Int -> List Int)
  lefschetzMotiv : List Int


/-- Motivic stabilization: [M_g] behaves asymptotically
in the Grothendieck ring as g ->   .
Relates to the Langlands program via motives. -/
def motivicClass (g : Nat) : List Int :=
  []

/-- The log minimal model program for M?_g:
M?_g(!=) = Proj   _{m  0} H^0(M?_g, ?m(K_{M?_g} + !=delta)?)
for !=  in  [0,1]    Q. As != decreases, we get birational
modifications of M?_g. -/
structure LogMinimalModel where
  genus : Nat
  alpha : Int   -- rational parameter, scaled
  moduliSpace : CoarseModuliSpace
  isLMMP : Bool


end MiniModuliSpaces


/-- Birational automorphisms of M_g: the group of birational
self-maps. For g >= 2, Bir(M_g) is finite (by Royden's theorem:
the Teichmuller metric determines the complex structure). -/
structure BirationalAutomorphismGroup where
  moduliSpace : CoarseModuliSpace
  isFinite : Bool
  generators : List (List Int)
  relations : List (List Int)


/-- The Torelli map: M_g -> A_g sending a curve to its Jacobian.
This is an immersion for g >= 2 (in characteristic 0).
The image is the locus of Jacobians (Schottky problem). -/
structure TorelliMap where
  source : CoarseModuliSpace
  target : CoarseModuliSpace
  isImmersion : Bool
  imageCodimension : Nat


/-- The Schottky problem: characterize which principally
polarized abelian varieties are Jacobians of curves. -/
theorem schottkyProblem : True := by trivial
