/-
# MiniCurvesSurfaces: Bridges — To Topology (L7)
-/

import MiniCurvesSurfaces.Core.Basic
import MiniCurvesSurfaces.Properties.Invariants

namespace MiniCurvesSurfaces

def algebraicCurveAsRiemannSurface (_g : Nat) : String := "Compact Riemann surface"
def topologicalGenusEqualsAlgebraicGenus (_g : Nat) : Bool := true

def fundamentalGroupOfCurve (g : Nat) : String :=
  match g with
  | 0 => "pi1(P1) = {1}"
  | 1 => "pi1(T^2) = Z x Z"
  | _ => s!"pi1(Sigma_{g}) generated by 2g loops with one relation"

def firstHomologyGroup (g : Nat) : String := s!"H1(C_{g}, Z) = Z^{2*g}"
def universalCover (g : Nat) : String :=
  match g with
  | 0 => "P1" | 1 => "C" | _ => "H (unit disk)"

def eulerCharFromGenus (g : Nat) : Int := 2 - 2 * (g : Int)

def geometryType (g : Nat) : String :=
  let chi := eulerCharFromGenus g
  if chi > 0 then "spherical" else if chi == 0 then "Euclidean" else "hyperbolic"

/-! ## Hodge Theory and Periods — L7 -/

def hodgeDecompositionCurve (g : Nat) : String :=
  "H^1(C,C) = H^(1,0) + H^(0,1), dim(H^(1,0)) = dim(H^(0,1)) = " ++ toString g

def periodMatrixDescription (g : Nat) : String :=
  s!"Period matrix: g x 2g complex matrix (Omega_1 | Omega_2)"

def schottkyProblem : String :=
  "Characterize which period matrices come from algebraic curves (solved)"

def teichmullerDimension (g : Nat) : Nat := 6*g - 6

def mappingClassGroupDescription (g : Nat) : String :=
  s!"M_{g} = T_{g} / Mod_{g}, dim_R(T_{g}) = {6*g - 6}"

def fenchelNielsenCoordinates (g : Nat) : String :=
  s!"{3*g-3} length + {3*g-3} twist = {6*g-6} real parameters"

/-! ## Uniformization Theorem — L7 -/

def uniformizationTheorem : String :=
  "Every simply connected Riemann surface is C, P1, or the unit disk H"

def fuchsianGroups (g : Nat) : String :=
  match g with
  | 0 => "Trivial (P1 -> P1)"
  | 1 => "Lattice Lambda in C (C -> C/Lambda)"
  | _ => s!"Fuchsian group Gamma in PSL(2,R), genus {g}"

def gagaPrinciple : String :=
  "Serre GAGA: algebraic = analytic for projective varieties over C"

/-! ## Period Matrices and Jacobians — L7

For a Riemann surface C of genus g, choose a symplectic basis
a_1,...,a_g, b_1,...,b_g of H_1(C,Z) with a_i·b_j = δ_ij.
Choose a basis ω_1,...,ω_g of H^0(C,Ω^1). The period matrix is:
  Ω = (A | B) where A_{ij} = ∫_{a_j} ω_i, B_{ij} = ∫_{b_j} ω_i

The Riemann matrix is τ = A^{-1}B, which is symmetric with Im(τ) > 0.
τ belongs to the Siegel upper half-space H_g of dimension g(g+1)/2.
The Jacobian is J(C) = C^g / (Z^g + τZ^g). -/

def siegelHalfSpaceDim (g : Nat) : Nat := g * (g + 1) / 2

def periodMatrixDim (g : Nat) : Nat := g * g

def jacobianAsComplexTorus (g : Nat) : String :=
  s!"J(C) = C^{g} / (Z^{g} + τZ^{g}), τ ∈ H_{g}"

/-! ## Symplectic Geometry of Moduli — L8

The moduli space M_g carries a natural symplectic structure
(the Weil-Petersson Kähler form). The cotangent space at C is
H^0(C, 2K_C) (= quadratic differentials). dim_C T^*M_g = 3g-3.

Fenchel-Nielsen coordinates: for a pants decomposition of a
hyperbolic surface, each pair of pants is parameterized by
3 length parameters and 3 twist parameters (total 6g-6). -/

def weilPeterssonForm : String :=
  "Weil-Petersson Kähler metric on T_g (and M_g)"

def cotangentSpaceModuliDim (g : Nat) : Nat := 3*g - 3

/-- The Mumford compactness criterion: the thick part of M_g
    (surfaces with injectivity radius ≥ ε) is compact.
    Degenerations correspond to pinching curves (Deligne-Mumford
    compactification M̄_g adding stable curves). -/

def mumfordCompactness : String :=
  "M_g thick part is compact; M̄_g adds stable nodal curves (Deligne-Mumford)"

/-! ## Brill-Noether Theory — L7

For a general curve C of genus g, the variety W^r_d(C) parameterizing
line bundles L with deg(L)=d and h^0(L) ≥ r+1 has dimension:
  ρ(g,r,d) = g - (r+1)(g-d+r)

W^r_d is nonempty iff ρ ≥ 0, and smooth of dim ρ when it is.
The Petri map μ: H^0(L)⊗H^0(K⊗L^{-1}) -> H^0(K) controls the local structure. -/

def brillNoetherDim (g r d : Nat) : Int :=
  (g : Int) - ((r : Int) + 1) * ((g : Int) - (d : Int) + (r : Int))

def brillNoetherExists (g r d : Nat) : Bool :=
  brillNoetherDim g r d >= 0

/-- Special divisors: deg(D) < g, h^0(D) > deg(D)-g+1.
    The gonality gon(C) = min{deg(f) | f: C -> P^1 non-constant}.
    For general curve: gon(C) = ⌊(g+3)/2⌋. -/

def gonalityGeneralCurve (g : Nat) : Nat := (g + 3) / 2

/-! ## Deformation Theory of Curves — L8

The Kodaira-Spencer map: T_{[C]} M_g ≅ H^1(C, T_C) where T_C is
the tangent sheaf. By Serre duality: H^1(C, T_C) ≅ H^0(C, 2K_C)^∨.
dim H^1(C, T_C) = 3g-3 for g ≥ 2.

Obstructions are in H^2(C, T_C) which vanishes for curves (dim C = 1),
so M_g is smooth (unobstructed deformations). -/

def kodairaSpencerDim (g : Nat) : Nat :=
  if g == 0 then 0 else if g == 1 then 1 else 3*g - 3

def curvesUnobstructed : String :=
  "Curves H^2(T_C) = 0 => unobstructed deformations => M_g smooth"

#eval fundamentalGroupOfCurve 0
#eval fundamentalGroupOfCurve 1
#eval fundamentalGroupOfCurve 2
#eval universalCover 0
#eval universalCover 1
#eval universalCover 5
#eval geometryType 0
#eval geometryType 1
#eval geometryType 2
#eval hodgeDecompositionCurve 3
#eval teichmullerDimension 2
#eval teichmullerDimension 3
#eval teichmullerDimension 5
#eval fuchsianGroups 0
#eval fuchsianGroups 1
#eval fuchsianGroups 2

#eval "── Periods and Deformation ──"
#eval siegelHalfSpaceDim 1
#eval siegelHalfSpaceDim 2
#eval siegelHalfSpaceDim 3
#eval jacobianAsComplexTorus 1
#eval jacobianAsComplexTorus 2
#eval weilPeterssonForm
#eval cotangentSpaceModuliDim 2
#eval cotangentSpaceModuliDim 3
#eval cotangentSpaceModuliDim 5
#eval mumfordCompactness
#eval brillNoetherDim 4 1 4
#eval brillNoetherDim 4 1 5
#eval brillNoetherDim 5 2 5
#eval brillNoetherExists 2 1 3
#eval brillNoetherExists 4 1 4
#eval gonalityGeneralCurve 3
#eval gonalityGeneralCurve 4
#eval gonalityGeneralCurve 5
#eval kodairaSpencerDim 0
#eval kodairaSpencerDim 1
#eval kodairaSpencerDim 2
#eval kodairaSpencerDim 3
#eval kodairaSpencerDim 5
#eval curvesUnobstructed

end MiniCurvesSurfaces