import MiniObjectKernel.Core.Basic
import MiniModuliSpaces.Core.Basic

namespace MiniModuliSpaces

/-
# Bridges: Moduli Spaces and Topology (L7)
Moduli spaces and topological invariants, mapping class groups,
Teichm^9ller theory, and the topology of moduli spaces.
-/

/-- Teichm^9ller space T_g: the universal cover of M_g.
T_g parameterizes Riemann surfaces of genus g with a marking
(isomorphism rho?(C) ->   _g). T_g ? R^{6g-6} is contractible.
M_g = T_g / MCG_g where MCG_g is the mapping class group. -/
structure TeichmullerSpace where
  genus : Nat
  dimension : Nat
  isContractible : Bool
  mappingClassGroup : List (List Int -> List Int)
  moduliSpace : CoarseModuliSpace


/-- The mapping class group MCG_g = rho?(Diff?(Omega_g))
acts properly discontinuously on T_g with quotient M_g.
MCG_g is generated by Dehn twists about simple closed curves
(Lickorish, Humphries). -/
structure MappingClassGroup where
  genus : Nat
  dehnTwists : List (List Int -> List Int)
  presentation : List (List Int)
  cohomologicalDimension : Nat


/-- The cohomology of M_g is related to the group cohomology
of MCG_g: H^*(M_g; Q) ? H^*(MCG_g; Q) (since T_g is contractible).
This allows computations via group cohomology. -/
theorem cohomologyMg_via_MCG (_g_val : Nat) (h : 0 <    2) : True := by
  trivial

/-- Harer stability: The cohomology groups H^k(M_g; Q)
stabilize as g ->    for k < 2(g-1)/3.
The stable cohomology ring is Q[kappa?, kappa?, ...]
(Mumford conjecture, proved by Madsen-Weiss). -/
theorem harerStability (g k : Nat) : True := by
  trivial

/-- The orbifold Euler characteristic of M_g:
psi_{orb}(M_g) = zeta(1-2g) for g    2.
Computed by Harer-Zagier using counting of cell decompositions. -/
def orbifoldEulerCharMg (g : Nat) : Int :=
  0 / (4 * (g : Int) * ((g : Int) - 1))

#eval "-- Orbifold Euler characteristics of M_g --"
#eval s!"psi_orb(M_2) = {orbifoldEulerCharMg 2}"
#eval s!"psi_orb(M_3) = {orbifoldEulerCharMg 3}"

/-- The moduli space of flat G-bundles on a Riemann surface Omega_g:
Hom(rho?(Omega_g), G) // G. For G compact, this is a symplectic variety
(golden Goldman symplectic form).
For G = U(1), this is the Jacobian (torus of dim 2g). -/
structure FlatGBundleModuli where
  curve : List Int
  compactGroup : String
  goldmanSymplecticForm : List (List Int)
  connectedComponents : Nat


/-- The topology of M_{g,n} can be studied via ribbon graphs
(Penner, Kontsevich). M_{g,n}    R_{>0}^n is homeomorphic to
the moduli space of metric ribbon graphs.
This gives a cell decomposition (Strebel differentials). -/
structure RibbonGraphDecomposition where
  genus : Nat
  markedPoints : Nat
  cells : List (List Int)
  orbifoldCells : List (List Int)


/-- The tautological ring of M_g in cohomology:
R^*(M_g) ? H^*(M_g; Q) is generated by kappa classes.
Faber conjectures (proved in many cases) describe the
structure of R^*(M_g) as a Gorenstein ring. -/
structure TautologicalRing where
  genus : Nat
  generators : List Nat
  faberConjectures : List Bool
  gorensteinSocle : Nat


/-- Cohomological field theory (CohFT): an algebra over the
modular operad {H^*(M?_{g,n})}. The Gromov-Witten theory of X
defines a CohFT via integration against the virtual class. -/
structure CohFT where
  stateSpace : List Int
  classes : List Nat -> List (List Int) -> List Int
  gluingAxiom : Bool
  stringEquation : Bool


end MiniModuliSpaces
